#!/bin/bash
# Simple Stock Analysis Script - One command, full analysis
# Usage: ./simple_analyze.sh TICKER [MARKET]
# Example: ./simple_analyze.sh MUTHOOTFIN NSE

TICKER="${1:-}"
MARKET="${2:-NSE}"
OUTPUT_FILE="TRADE-ANALYSIS-${TICKER}.md"

if [ -z "$TICKER" ]; then
    echo "Error: Ticker required"
    echo "Usage: $0 TICKER [MARKET]"
    echo "Example: $0 MUTHOOTFIN NSE"
    exit 1
fi

echo "🚀 Analyzing $TICKER ($MARKET)..."
echo "This will take 3-5 minutes. Please wait..."
echo ""

# Create comprehensive analysis prompt
cat <<EOF | claude --model sonnet > "$OUTPUT_FILE"
Perform a comprehensive multi-dimensional stock analysis for ${TICKER} listed on ${MARKET}.

Today's date: $(date +"%B %d, %Y")

## ANALYSIS FRAMEWORK

Conduct thorough research using WebSearch and WebFetch tools to analyze ${TICKER} across 5 dimensions:

### 1. TECHNICAL ANALYSIS (Weight: 25%)
Score 0-100, broken into:
- Trend Score (0-20): Moving averages, price position, higher highs/lows
- Momentum Score (0-20): RSI, MACD, Stochastic indicators
- Volume Score (0-20): Volume vs averages, OBV, accumulation/distribution
- Pattern Quality (0-20): Chart patterns (flags, triangles, H&S, etc.)
- Relative Strength (0-20): Performance vs benchmark index

Provide:
- Current price and recent performance
- Key support levels (at least 3 with confluence reasoning)
- Key resistance levels (at least 3 with confluence reasoning)
- Entry zone recommendation
- Stop-loss level (with % risk)
- Target 1 (conservative) and Target 2 (aggressive)
- Technical Signal: Bullish / Neutral / Bearish

### 2. FUNDAMENTAL ANALYSIS (Weight: 25%)
Score 0-100, broken into:
- Valuation (0-20): P/E, P/B, PEG vs peers and historical
- Growth (0-20): Revenue, earnings, guidance, TAM
- Profitability (0-20): Margins, ROE, ROIC
- Financial Health (0-20): Debt, cash flow, liquidity
- Moat Strength (0-20): Competitive advantages (Wide/Narrow/None)

Provide:
- Current valuation metrics with peer comparison
- Growth trajectory and sustainability
- Profitability analysis
- Balance sheet assessment
- Moat quality evaluation
- Verdict: Undervalued / Fair Value / Overvalued
- Fundamental Signal: Strong / Adequate / Weak

### 3. SENTIMENT ANALYSIS (Weight: 20%)
Score 0-100, broken into:
- News Sentiment (0-20): Recent headlines, catalysts
- Social Media (0-20): Reddit, Twitter discussion
- Analyst Ratings (0-20): Consensus, price targets, upgrades/downgrades
- Institutional Activity (0-20): FII/DII flows, ownership trends
- Insider/Derivatives (0-20): Promoter activity, short interest, put/call ratios

Provide:
- Recent news assessment (positive/negative/neutral)
- Retail sentiment direction
- Professional analyst views
- Smart money signals
- Sentiment Signal: Bullish / Neutral / Bearish

### 4. RISK ASSESSMENT (Weight: 15%)
Score 0-100 where HIGHER = LOWER RISK, broken into:
- Volatility (0-20): Historical vol, beta, ATR
- Downside Protection (0-20): Bear case scenarios, max drawdown
- Macro Resilience (0-20): Interest rate, regulatory, correlation risks
- Liquidity (0-20): Trading volume, spreads, float
- Risk/Reward (0-20): R/R ratio at current price

Provide:
- Volatility profile
- Key downside scenarios with bear case target
- Top 5-10 risks ranked by probability × impact
- Position sizing recommendations (conservative/moderate/aggressive)
- Risk Level: Low / Moderate / High / Extreme

### 5. INVESTMENT THESIS (Weight: 15%)
Score 0-100, broken into:
- Catalyst Clarity (0-20): Clear, identifiable catalysts
- Timing (0-20): Is timing right for entry
- Asymmetry (0-20): Risk/reward skew
- Edge (0-20): Informational or analytical edge
- Conviction (0-20): Overall confidence

Provide:
- Core Thesis (2-3 sentences: why this stock, why now)
- Bull Case: 5-7 catalysts, bull target (12m), probability
- Bear Case: 5-7 risks, bear target (12m), probability
- Catalyst Calendar: Upcoming events with dates and impact
- Entry/Exit Strategy: Entry zone, stop-loss, targets, timeframe
- Conviction Assessment: What gives/reduces conviction, invalidation triggers
- Thesis Signal: Strong / Moderate / Weak

## COMPOSITE SCORING

Calculate:
Composite Score = (Technical × 0.25) + (Fundamental × 0.25) + (Sentiment × 0.20) + (Risk × 0.15) + (Thesis × 0.15)

Grade Mapping:
- 85-100: A+ (Strong Buy)
- 70-84: A (Buy)
- 55-69: B (Hold/Accumulate)
- 40-54: C (Neutral)
- 25-39: D (Caution)
- 0-24: F (Avoid)

## OUTPUT FORMAT

Generate a comprehensive markdown report with this EXACT structure:

\`\`\`markdown
# Trade Analysis: ${TICKER}
> Generated by AI Trading Analyst | $(date +"%B %d, %Y")

---

## Executive Summary

[2-3 paragraph synthesis: What is this company, what is the setup, what is the verdict?]

---

## Trade Score Dashboard

| Dimension | Score | Weight | Weighted |
|-----------|-------|--------|----------|
| Technical Strength | X/100 | 25% | X.X |
| Fundamental Quality | X/100 | 25% | X.X |
| Sentiment & Momentum | X/100 | 20% | X.X |
| Risk Profile | X/100 | 15% | X.X |
| Thesis Conviction | X/100 | 15% | X.X |
| **Composite Trade Score** | | | **X/100** |

**Grade: [X]** | **Signal: [X]**

### Sub-Score Breakdown

**Technical [X/100]:** Trend X/20 | Momentum X/20 | Volume X/20 | Pattern X/20 | Rel Strength X/20
**Fundamental [X/100]:** Valuation X/20 | Growth X/20 | Profitability X/20 | Health X/20 | Moat X/20
**Sentiment [X/100]:** News X/20 | Social X/20 | Analysts X/20 | Institutional X/20 | Insider X/20
**Risk [X/100]:** Volatility X/20 | Downside X/20 | Macro X/20 | Liquidity X/20 | R/R X/20
**Thesis [X/100]:** Catalyst X/20 | Timing X/20 | Asymmetry X/20 | Edge X/20 | Conviction X/20

---

## Technical Overview

[Summary with key levels]

**Key Levels:**
- Support: ₹X, ₹X, ₹X
- Resistance: ₹X, ₹X, ₹X
- Entry Zone: ₹X - ₹X
- Stop Loss: ₹X (X% risk)
- Target 1: ₹X (X% upside)
- Target 2: ₹X (X% upside)

---

## Fundamental Overview

[Summary with valuation verdict]

**Key Metrics:**
- P/E: X.Xx
- ROE: X%
- Revenue Growth: X%
- Net Margin: X%
- Verdict: [Undervalued/Fair/Overvalued]

---

## Sentiment Analysis

[Summary with consensus view]

**Key Findings:**
- Analyst Consensus: [Buy/Hold/Sell]
- Average Price Target: ₹X (X% upside/downside)
- Institutional Sentiment: [Positive/Neutral/Negative]

---

## Risk Assessment

[Summary with risk level]

**Top Risks:**
1. [Risk 1]
2. [Risk 2]
3. [Risk 3]

**Position Sizing:**
- Conservative: X%
- Moderate: X%
- Aggressive: X%

---

## Investment Thesis

**Core Thesis:** [2-3 sentences]

**Bull Case (Target: ₹X, Probability: X%):**
- [Catalyst 1]
- [Catalyst 2]
- [Catalyst 3]

**Bear Case (Target: ₹X, Probability: X%):**
- [Risk 1]
- [Risk 2]
- [Risk 3]

---

## Entry/Exit Strategy

| Parameter | Level | Notes |
|-----------|-------|-------|
| Entry Zone | ₹X - ₹X | [reasoning] |
| Stop Loss | ₹X | X% risk |
| Target 1 | ₹X | X% reward (conservative) |
| Target 2 | ₹X | X% reward (aggressive) |
| Risk/Reward | X:1 | [assessment] |
| Position Size | X% | [conservative/moderate/aggressive] |
| Timeframe | [swing/position/long-term] | [reasoning] |

---

## Bull vs Bear

| Bull Case | Bear Case |
|-----------|-----------|
| [factor 1] | [factor 1] |
| [factor 2] | [factor 2] |
| [factor 3] | [factor 3] |
| **Bull Target: ₹X** | **Bear Target: ₹X** |

---

## Catalyst Calendar

| Date/Period | Event | Expected Impact |
|-------------|-------|-----------------|
| [date] | [event] | [bullish/bearish/neutral] |

---

> **DISCLAIMER:** This analysis is for educational and research purposes only. NOT financial advice.
> Always conduct your own due diligence and consult qualified financial advisors before making investment decisions.

---

**Report Generated:** $(date +"%B %d, %Y")
**Ticker:** ${TICKER}
**Market:** ${MARKET}
**Composite Score:** X/100
**Grade:** [X]
**Signal:** [X]
\`\`\`

## IMPORTANT INSTRUCTIONS

1. Use WebSearch extensively to gather current, accurate data
2. Be specific with numbers, prices, and percentages (never vague)
3. Provide actual dates for catalyst calendar, not placeholders
4. Calculate all scores mathematically and show the math
5. Ensure consistency between scores, grade, and signal
6. Include both bullish and bearish perspectives
7. Make entry/exit levels actionable and specific
8. Cite recent news and analyst reports with dates
9. Compare to relevant peers and benchmarks
10. Focus on actionable insights, not generic commentary

BEGIN ANALYSIS NOW.
EOF

echo ""
echo "✅ Analysis complete!"
echo "📄 Report saved to: $OUTPUT_FILE"
echo ""
echo "View with: cat $OUTPUT_FILE"
echo "Or open in editor: code $OUTPUT_FILE"
echo ""
